(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const groups=window.EXAM_INDEX||[], all=groups.flatMap(g=>g.passages.map(p=>({...p,group:g.id,type:g.name})));
let saved={};try{saved=JSON.parse(localStorage.getItem('yeolgong.study.v2')||'{}')}catch{}
if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};
let mode='analysis', section='flow', current=null, request=0, filter='all', query='', status='all', font=Number(saved.font)||18;
const pending=new Map(), app=$('#app');
const getMark=id=>saved[id]||{};
function persist(){try{localStorage.setItem('yeolgong.study.v2',JSON.stringify(saved))}catch{notify('저장 공간을 사용할 수 없습니다. 이 창에서만 유지됩니다.')}}
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();const m=$('#main');if(m){m.tabIndex=-1;m.focus()}});
let noticeTimer;function notify(text){$('#notice').textContent=text;$('#notice').classList.add('show');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').classList.remove('show'),2500)}
function load(g){if(window.EXAM_DATA?.[g.id])return Promise.resolve(window.EXAM_DATA[g.id]);if(pending.has(g.id))return pending.get(g.id);const promise=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=g.file;s.onload=()=>window.EXAM_DATA?.[g.id]?resolve(window.EXAM_DATA[g.id]):reject(Error('자료 형식을 확인해 주세요.'));s.onerror=()=>{s.remove();reject(Error('자료를 불러오지 못했습니다.'));};document.head.append(s)}).finally(()=>pending.delete(g.id));pending.set(g.id,promise);return promise}
function brand(){return '<a class="brand" href="#">열공<span>·</span><small>문장 사이를 읽다</small></a>'}
function library(){current=null;document.title='열공 · 문장 사이를 읽다';app.innerHTML=`<header class="site-header">${brand()}<span class="edition">ENGLISH STUDY / 02</span></header><main id="main" class="library"><section class="hero"><div><p class="eyebrow">READ THE LOGIC</p><h1>해석을 넘어,<br>문장 사이의 이유를 읽다.</h1><p>전체 흐름에서 한 문장의 역할까지.<br>지문을 깊이 읽고, 수능의 여러 유형으로 다시 바라보세요.</p></div><div class="summary"><span>이번 시험의 읽기 자료</span><strong>${all.length}<small>지문</small></strong><div>${groups.length}개 유형 <span>·</span> 전체 시험 범위</div><div id="progressText"></div><div class="progress-track"><i id="progressBar"></i></div></div></section><section class="library-tools" aria-label="지문 찾기"><div class="tool-row"><h2>학습 서재 <span>${all.length}</span></h2><label class="search"><span>검색</span><input id="search" type="search" placeholder="주제, 출처, 지문 이름" value="${esc(query)}"></label></div><div class="filters" aria-label="원래 문제 유형"><button data-filter="all">전체 <small>${all.length}</small></button>${groups.map(g=>`<button data-filter="${g.id}">${g.name} <small>${g.passages.length}</small></button>`).join('')}</div><div class="list-toolbar"><p class="muted">원래 출제 유형별 108지문과 어법 특별 자료 7지문입니다.</p><label>학습 상태 <select id="status"><option value="all">전체</option><option value="star">보관한 지문</option><option value="done">학습 완료</option><option value="new">아직 읽지 않음</option></select></label></div></section><div id="cards" class="cards"></div><aside class="special-banner"><b>어법 특별 · 캐서린의 어법 Finish</b><p>2020~2026학년도 7지문 · 문장별 직역 + 밑줄 35곳 집중 분석</p><a class="button" href="#grammar-special-2020">특별 자료 시작하기 →</a></aside><footer class="library-footer"><b>두 번의 읽기</b><span>01 지문 분석 · 왜 이 문장이 여기에 있을까?</span><span>02 수능 유형 대비 · 이 논리는 어떻게 출제될까?</span><small>학습 표시와 메모는 이 브라우저에 저장됩니다.</small></footer></main>`;
$('#search').addEventListener('input',e=>{query=e.target.value;cards()});$('#status').value=status;$('#status').onchange=e=>{status=e.target.value;cards()};$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;cards()});cards()}
function cards(){const done=all.filter(p=>getMark(p.id).done).length;$('#progressText').textContent=`${done} / ${all.length} 학습 완료`;$('#progressBar').style.width=`${all.length?done/all.length*100:0}%`;$$('[data-filter]').forEach(b=>{b.classList.toggle('selected',b.dataset.filter===filter);b.setAttribute('aria-pressed',String(b.dataset.filter===filter))});const list=all.filter(p=>(filter==='all'||p.group===filter)&&(!query||`${p.title} ${p.source} ${p.central} ${p.type}`.toLowerCase().includes(query.toLowerCase()))&&(status==='all'||(status==='star'?getMark(p.id).star:status==='done'?getMark(p.id).done:!getMark(p.id).done)));
$('#cards').innerHTML=list.length?list.map(p=>`<a class="passage-card" href="#${p.id}"><div class="card-top"><span class="type-tag">${p.type}</span><span>${getMark(p.id).star?'★ ':''}${getMark(p.id).done?'✓ 완료':String(p.num).padStart(2,'0')}</span></div><h3>${esc(p.title)}</h3><p>${esc(p.central)}</p><div class="card-bottom"><span>${esc(p.source)}</span><span>${p.count}문장 ↗</span></div></a>`).join(''):'<div class="empty"><h3>조건에 맞는 지문이 없습니다.</h3><p>검색어나 학습 상태 필터를 바꿔 보세요.</p></div>'}
const navs={analysis:[['flow','전체 흐름'],['easy','쉬운 설명'],['sentences','문장 연결'],['logic','전환·범위'],['language','지시·구문'],['summary','핵심 정리']],prep:[['answers','주제·요지·제목'],['order','순서'],['positions','삽입·빈칸'],['words','어법·어휘']]};
const specialNavs={analysis:[['brief','간단 이해'],['sentences','문장 연결']],prep:[['grammar','밑줄 어법 5곳'],['patterns','유형별 판단법']]};
const activeNavs=()=>current?.specialGrammar?specialNavs:navs;
async function route(){const ticket=++request;let id;try{id=decodeURIComponent(location.hash.slice(1))}catch{id=''}if(!id){library();return}const meta=all.find(p=>p.id===id);if(!meta){library();notify('해당 지문을 찾지 못해 목록을 열었습니다.');return}app.innerHTML=`<header class="site-header">${brand()}</header><main id="main" class="empty" role="status">지문과 분석을 불러오는 중입니다…</main>`;try{const data=await load(groups.find(g=>g.id===meta.group));if(ticket!==request)return;current=data.find(p=>p.id===id);if(!current)throw Error('지문을 찾을 수 없습니다.');mode=current.specialGrammar?'prep':'analysis';section=current.specialGrammar?'grammar':'flow';study()}catch(e){if(ticket!==request)return;app.innerHTML=`<header class="site-header">${brand()}</header><main id="main" class="empty"><h2>${esc(e.message)}</h2><p>자료 파일이 같은 폴더에 있는지 확인해 주세요.</p><button id="retry">다시 불러오기</button><a class="button" href="#">목록</a></main>`;$('#retry').onclick=route}}
function study(){const p=current,i=all.findIndex(x=>x.id===p.id);document.title=`${p.title} · 열공`;app.innerHTML=`<header class="study-header"><a class="back" href="#" aria-label="학습 서재로 돌아가기">← <span>학습 서재</span></a><div class="study-title"><span>${p.type} ${String(p.num).padStart(2,'0')} <i>·</i> ${esc(p.source)}</span><h1>${esc(p.title)}</h1></div><div class="study-actions"><button id="star" aria-label="지문 보관"></button><button id="done"></button></div></header><main id="main" class="study-main"><div class="reading-layout"><aside class="original-pane" aria-label="영어 원문"><div class="original-toolbar"><span class="eyebrow">PASSAGE</span><div><button id="smaller" aria-label="원문 글자 줄이기">A−</button><button id="larger" aria-label="원문 글자 키우기">A＋</button><button id="gloss" aria-pressed="${saved.gloss!==false}">${saved.gloss===false?'직역 보기':'직역 숨기기'}</button><button id="source">사진 원본 ↗</button></div></div><div class="source-info"><span>${p.sentences.length}문장</span><span>S 번호는 학습용 문장 번호입니다.</span></div>${p.specialGrammar?'<p class="source-warning">어법 특별 자료 · 밑줄 ①~⑤ 모두 분석합니다. 틀린 출제 표현은 영어에 보존했고 직역은 교정한 의미입니다.</p>':p.edits?'<p class="source-warning">사진 원문의 출제 오류를 밑줄로 표시했습니다. 교정 내용은 해당 문장과 어법·어휘 영역에서 확인하세요.</p>':''}${p.irrelevant?'<p class="source-warning">흐름과 무관한 문장도 원문대로 보존했습니다. 해당 문장은 별도로 표시합니다.</p>':''}${p.sequence?`<p class="source-warning">읽기 순서 <b>${p.sequence}</b>로 연결했습니다. 원래 A·B·C 구획은 아래에 표시합니다.</p>`:''}${p.originalBlank?'<p class="source-warning">빈칸의 답을 채운 학습용 본문입니다. 채운 표현은 색으로 표시하며, 원문은 사진에서 확인할 수 있습니다.</p>':''}<div id="original" class="original ${saved.gloss===false?'hide-gloss':''}" style="--reading-size:${font}px">${p.sentences.map(s=>`${blockLabel(p,s.n)}<button class="sentence ${s.n===p.irrelevant?'irrelevant':''}" data-s="${s.n}" aria-label="S${s.n} 문장 분석 보기"><span class="sentence-num">${String(s.n).padStart(2,'0')}</span><span class="sentence-body"><span class="sentence-en" lang="en">${originalText(p,s)}</span><span class="sentence-ko" lang="ko"><span class="gloss-label">직역</span>${esc(s.literal||s.ko)}</span></span>${s.n===p.irrelevant?'<em>흐름과 무관</em>':''}</button>`).join('')}</div><div class="original-footer">문장을 누르면 해석과 앞뒤 연결로 이동합니다.</div><div class="passage-nav"><button id="prev" ${i===0?'disabled':''}>← 이전 지문</button><span>${i+1} / ${all.length}</span><button id="next" ${i===all.length-1?'disabled':''}>다음 지문 →</button></div></aside><section class="analysis-pane" aria-label="학습 해설"><div class="mode-tabs" role="tablist" aria-label="학습 영역"><button role="tab" id="analysisTab" data-mode="analysis" aria-controls="studyContent">01 <strong>${p.specialGrammar?'내용·문장 연결':'지문 분석'}</strong></button><button role="tab" id="prepTab" data-mode="prep" aria-controls="studyContent">02 <strong>${p.specialGrammar?'어법 집중 분석':'수능 유형 대비'}</strong></button></div><nav id="sectionNav" class="section-nav" aria-label="해설 목차"></nav><div id="studyContent" class="study-content" role="tabpanel" tabindex="0"></div></section></div></main>`;
$('#star').onclick=()=>toggle('star');$('#done').onclick=()=>toggle('done');updateMarks();$('#smaller').onclick=()=>resize(-1);$('#larger').onclick=()=>resize(1);$('#source').onclick=photos;$('#gloss').onclick=()=>{saved.gloss=saved.gloss===false;persist();$('#original').classList.toggle('hide-gloss',!saved.gloss);$('#gloss').textContent=saved.gloss?'직역 숨기기':'직역 보기';$('#gloss').setAttribute('aria-pressed',String(saved.gloss))};$('#prev').onclick=()=>location.hash=all[i-1].id;$('#next').onclick=()=>location.hash=all[i+1].id;
$$('[data-s]').forEach(b=>b.onclick=()=>showSentence(Number(b.dataset.s)));$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;section=activeNavs()[mode][0][0];renderContent()});$$('[role="tab"]').forEach((b,i,a)=>b.onkeydown=e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const next=e.key==='Home'?0:e.key==='End'?a.length-1:(i+1)%a.length;a[next].click();a[next].focus()}});renderContent()}
function blockLabel(p,n){if(!p.sequence)return '';if(n===1)return '<div class="block-label">주어진 글</div>';const b=p.order.find(b=>b[0]===n);return b?`<div class="block-label">${esc(b[2])}</div>`:''}
function originalText(p,s){let t=esc(s.en);if(p.originalBlank&&s.n===p.blank[0])t=t.replace(esc(p.blank[1]),`<mark class="source-fill" title="원래 빈칸에 들어갈 표현">${esc(p.blank[1])}</mark>`);if(p.specialGrammar){for(const g of p.grammarPoints.filter(g=>g.n===s.n))t=t.replace(esc(g.quote),`<mark class="grammar-target"><sup>${'①②③④⑤'[g.number-1]}</sup> ${esc(g.quote)}</mark>`);return t;}for(const e of p.edits||[])if(e[0]===s.n)t=t.replace(esc(e[1]),`<u class="source-error">${esc(e[1])}</u>`);return t}
function resize(d){font=Math.min(24,Math.max(16,font+d));$('#original').style.setProperty('--reading-size',`${font}px`);saved.font=font;persist()}
function toggle(key){saved[current.id]={...getMark(current.id),[key]:!getMark(current.id)[key]};persist();updateMarks()}
function updateMarks(){const m=getMark(current.id);$('#star').textContent=m.star?'★ 보관 중':'☆ 보관';$('#star').setAttribute('aria-pressed',String(!!m.star));$('#done').textContent=m.done?'✓ 학습 완료':'완료 표시';$('#done').setAttribute('aria-pressed',String(!!m.done))}
function pick(a,b=a){$$('[data-s]').forEach(x=>x.classList.toggle('active',Number(x.dataset.s)>=a&&Number(x.dataset.s)<=b));const el=$(`[data-s="${a}"]`);if(el){const pane=$('.original-pane');pane.scrollTo({top:Math.max(0,el.getBoundingClientRect().top-pane.getBoundingClientRect().top+pane.scrollTop-$('.original-toolbar').offsetHeight-12),behavior:'smooth'})}}
function showSentence(n){mode='analysis';section='sentences';renderContent();pick(n);const card=$(`#analysis-s${n}`);if(card){const pane=$('#studyContent');pane.scrollTo({top:card.getBoundingClientRect().top-pane.getBoundingClientRect().top+pane.scrollTop-16,behavior:'smooth'});card.classList.add('selected-card')}if(innerWidth<720&&card)card.scrollIntoView({behavior:'smooth',block:'start'})}
const range=(a,b=a)=>`<button class="ref-button" data-range="${a},${b}">S${a}${b!==a?'–'+b:''} ↖</button>`;
const heading=(num,title,sub='')=>`<div class="section-heading"><span class="eyebrow">${num}</span><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>`;
const quote=(p,n)=>`<blockquote lang="en">${esc(p.sentences[n-1].en)}</blockquote>`;
function flow(p){return `<div class="flow-list">${p.flow.map((f,i)=>`<article class="flow-step"><span class="step-number">${i+1}</span><div><h3>${esc(f[0])} ${range(f[1],f[2])}</h3><p>${esc(f[3])}</p></div></article>`).join('')}</div>`}
function edits(p,n){return (p.edits||[]).filter(e=>!n||e[0]===n).map(e=>`<div class="correction"><span>출제 표현 교정 ${range(e[0])}</span><p><del>${esc(e[1])}</del> → <b>${esc(e[2])}</b></p><p>${esc(e[3])}</p></div>`).join('')}
function renderContent(){const p=current;$$('[data-mode]').forEach(b=>{const on=b.dataset.mode===mode;b.setAttribute('aria-selected',String(on));b.tabIndex=on?0:-1});$('#studyContent').setAttribute('aria-labelledby',mode==='analysis'?'analysisTab':'prepTab');$('#sectionNav').innerHTML=activeNavs()[mode].map(([key,label])=>`<button data-section="${key}" ${section===key?'aria-current="true"':''}>${label}</button>`).join('');$$('[data-section]').forEach(b=>b.onclick=()=>{section=b.dataset.section;renderContent()});let html='';
if(p.specialGrammar&&section!=='sentences'){html=specialContent(p);}else if(mode==='analysis'){
 if(section==='easy')html=heading('EASY READ','쉬운 설명','먼저 상황을 이해하고, 그다음 문장 사이의 이유를 읽어 보세요.')+`<div class="easy-intro"><span>이 글이 하려는 말</span><p>${esc(p.central)}</p></div><div class="easy-story">${p.easy.map((t,i)=>`<article><span class="easy-number">${i+1}</span><p>${esc(t)}</p></article>`).join('')}</div><div class="content-card easy-check"><h3>이 차이만 기억하기</h3><p>${esc(p.tip)}</p></div><div class="arrow-flow">${p.flow.map(f=>`<span>${esc(f[0])}</span>`).join('<i>↓</i>')}</div><button class="primary" data-go="sentences">이해한 내용으로 문장 읽기 →</button>`;
 if(section==='flow')html=heading('01 / FIRST READ','전체 흐름 먼저','세부 해석 전에, 다음 내용이 필요한 이유부터 확인하세요.')+flow(p)+`<div class="takeaway"><span>읽기의 출발점</span><p>${esc(p.tip)}</p></div><button class="primary" data-go="sentences">이 흐름으로 문장 읽기 →</button>`;
 if(section==='sentences')html=heading('02 / SENTENCE LOGIC','문장별 해석과 기능','영문 → 자연스러운 해석 → 앞뒤 연결. 원문의 문장 번호와 함께 읽으세요.')+p.sentences.map(s=>`<article id="analysis-s${s.n}" class="sentence-card"><div class="card-top">${range(s.n)}<span class="role-tag">${esc(s.role)}</span></div><p lang="en" class="sentence-quote">${esc(s.en)}</p><p class="translation">${esc(s.ko)}</p><div class="reason"><b>왜 여기 있는가</b><p>${esc(s.why)}</p></div>${edits(p,s.n)}</article>`).join('');
 if(section==='logic')html=heading('03 / CONNECTORS','연결어가 바꾸는 논리')+p.connectors.map(c=>`<article class="content-card"><h3><span lang="en">${esc(c[1])}</span> ${range(c[0])}</h3><div class="before-after"><div><span>이전</span><p>${esc(c[2])}</p></div><div><span>이후</span><p>${esc(c[3])}</p></div></div></article>`).join('')+heading('04 / COMPARISON','모순처럼 보이는 부분 비교','주어·대상·범위·조건과 주장 주체 중 실제 차이를 만드는 축을 비교합니다.')+p.compare.map(c=>`<article class="content-card"><div class="comparison"><b>${esc(c[0])}</b><span>↔</span><b>${esc(c[1])}</b></div><p class="axis">비교 기준 · ${esc(c[2])}</p><p>${esc(c[3])}</p></article>`).join('')+heading('05 / SCOPE','같은 말처럼 보여도 범위는 다르다')+`<div class="content-card"><p>${esc(p.tip)}</p>${p.compare.map(c=>`<p><b>${esc(c[2])}</b><br>${esc(c[0])}와 ${esc(c[1])}를 같은 뜻으로 합치지 말고, 위의 조건과 범위를 적용해 읽습니다.</p>`).join('')}</div>`;
 if(section==='language')html=heading('06 / REFERENCES','지시어가 가리키는 것','명사 하나를 받는지, 앞선 내용 전체를 받는지 구분합니다.')+`<div class="reference-list">${p.refs.map(r=>`<article><div>${range(r[0])}<strong lang="en">${esc(r[1])}</strong></div><p>↳ ${esc(r[2])}</p></article>`).join('')}</div>`+heading('07 / STRUCTURE','어려운 문장만 뼈대 잡기')+p.syntax.map(s=>`<article class="content-card">${range(s[0])}${quote(p,s[0])}<p>${esc(s[1])}</p></article>`).join('');
 if(section==='summary')html=heading('08 / CLAIM & EVIDENCE','주장과 설명을 구분하기')+`<div class="takeaway"><span>사례를 포괄하는 핵심 주장</span><p>${esc(p.central)}</p></div><div class="role-map">${p.sentences.map(s=>`<div>${range(s.n)}<b>${esc(s.role)}</b><p>${esc(s.why)}</p></div>`).join('')}</div>`+heading('09 / TURNING POINT','핵심 전환점')+(p.turns||[p.connectors[0][0]]).map(n=>`<article class="content-card"><h3>${esc(p.sentences[n-1].role)} ${range(n)}</h3>${quote(p,n)}<p>${esc(p.sentences[n-1].why)}</p></article>`).join('')+heading('11 / ORIGINAL QUESTION','원래 문제의 판단 근거','새 문제를 만든 것이 아니라 사진에 실린 원래 문제의 정답과 근거입니다.')+`<details class="content-card"><summary>원래 문제 정답·해설 펼치기</summary>${answerExplanation(p)}</details>`+heading('10 · 12 / FINAL READ','전체 논리와 최종 요약')+`<div class="arrow-flow">${p.flow.map(f=>`<span>${esc(f[0])}</span>`).join('<i>↓</i>')}</div><div class="takeaway"><span>[한 문장 핵심]</span><p>${esc(p.central)}</p></div><div class="content-card"><b>[읽을 때 가장 중요한 포인트]</b><p>${esc(p.tip)}</p></div>`+note(p);
}else{
 if(section==='answers')html=heading('01 / BIG PICTURE','주제 · 요지 · 제목','출제 대비용 표현 예시입니다. 새 문제나 공식 정답이 아닙니다.')+`<article class="answer-card"><span>예상 주제 · 무엇에 관한 글인가</span><h3 lang="en">${esc(p.topicEN)}</h3></article><article class="answer-card"><span>예상 요지 · 저자가 말하려는 바</span><h3>${esc(p.central)}</h3></article><article class="answer-card"><span>예상 제목 · 글 전체를 포괄하는 표현</span><h3 lang="en">${esc(p.titleEN)}</h3><p>${esc(p.title)}</p></article><div class="content-card"><h3>선지를 볼 때 확인할 변형</h3><div class="checks"><span>원인 ↔ 결과</span><span>주체 변경</span><span>일부 ↔ 전체</span><span>가능성 ↔ 필연</span><span>긍정 ↔ 부정</span><span>시간 순서</span><span>목적 ↔ 결과</span><span>예시 ↔ 중심 주장</span></div><p>${esc(p.tip)}</p></div><details class="content-card"><summary>사진의 원래 문제 해설</summary>${answerExplanation(p)}</details>`;
 if(section==='order')html=heading('02 / ORDER','논리 덩어리로 나누기',p.sequence?`원래 단락 표기를 유지한 정리 순서: ${p.sequence}`:'학습을 위한 A·B·C 구획입니다. 실제 문제를 출제한 것은 아닙니다.')+(p.introCount?`<article class="content-card"><h3>주어진 글 ${range(1,p.introCount)}</h3><p lang="en">${esc(p.sentences.slice(0,p.introCount).map(s=>s.en).join(' '))}</p></article>`:'')+p.order.map((o,i)=>`<article class="order-card"><span class="order-letter">${p.sequence?esc(p.sequence.split(' → ')[i]):'ABC'[i]}</span><div><h3>${esc(o[2])} ${range(o[0],o[1])}</h3><p lang="en">${esc(p.sentences.slice(o[0]-1,o[1]).filter(s=>s.n!==p.irrelevant).map(s=>s.en).join(' '))}</p></div></article>`).join('')+`<div class="takeaway"><span>다음 덩어리가 필요한 이유</span><p>${p.flow.map(f=>esc(f[0])+': '+esc(f[3])).join('<br>↓<br>')}</p></div>${p.irrelevant?`<p class="muted">S${p.irrelevant}은 무관한 문장이므로 논리 구획에서 제외했습니다.</p>`:''}`;
 if(section==='positions')html=heading('03 / INSERTION','삽입에 주목할 문장','문장을 지우거나 새 문제를 내지 않고, 제자리에 있어야 하는 단서를 읽습니다.')+`<article class="content-card">${range(p.insert[0])}${quote(p,p.insert[0])}<div class="position-context"><span>앞: ${p.insert[0]>1?'S'+(p.insert[0]-1):'글의 시작'}</span><b>→ S${p.insert[0]} →</b><span>뒤: ${p.insert[0]<p.sentences.length?'S'+(p.insert[0]+1):'글의 끝'}</span></div><p>${esc(p.insert[1])}</p></article>`+heading('04 / BLANK','빈칸으로 바뀌기 쉬운 핵심 표현')+`<article class="content-card">${range(p.blank[0])}<h3 class="blank-phrase" lang="en">${esc(p.blank[1])}</h3>${quote(p,p.blank[0])}<div class="reason"><b>이 표현을 복원할 근거</b><p>${esc(p.blank[2])}</p></div></article><div class="takeaway"><span>상위 논리 확인</span><p>${esc(p.central)}</p></div>`;
 if(section==='words')html=heading('05 / GRAMMAR','주요 어법',p.edits?'사진의 출제 표현과 권장 교정을 함께 확인하세요.':'문장 구조가 의미와 연결되는 부분에 집중하세요.')+edits(p)+p.syntax.map(s=>`<article class="content-card">${range(s[0])}${quote(p,s[0])}<p>${esc(s[1])}</p></article>`).join('')+heading('06 / VOCABULARY','주요 어휘와 논리 속 역할')+`<div class="vocab-list">${p.vocab.map(v=>`<article><h3 lang="en">${esc(v[0])}</h3><strong>${esc(v[1])}</strong><p>${esc(v[2])}</p></article>`).join('')}</div>`+note(p);
}
$('#studyContent').innerHTML=html;$('#studyContent').scrollTop=0;$$('[data-range]').forEach(b=>b.onclick=()=>{const [a,z]=b.dataset.range.split(',').map(Number);pick(a,z)});$$('[data-go]').forEach(b=>b.onclick=()=>{section=b.dataset.go;renderContent()});const n=$('#note');if(n)n.addEventListener('input',()=>{saved[p.id]={...getMark(p.id),note:n.value};persist();$('#noteState').textContent='이 브라우저에 저장됨'});
}
function grammarCard(g){return `<article class="content-card grammar-card"><div class="card-top"><span class="role-tag">${g.number?'①②③④⑤'[g.number-1]+' · ':''}${esc(g.category)}</span>${range(g.n)}</div><h3 lang="en">${esc(g.quote)}</h3>${g.number?`<p class="grammar-verdict ${g.replacement?'fix':''}">${g.replacement?'교정 필요 → <b lang="en">'+esc(g.replacement)+'</b>':'원문 표현이 맞습니다'}</p>`:''}<div class="reason"><b>판단 근거</b><p>${esc(g.rule)}</p></div><div class="grammar-trap"><b>헷갈리지 않기</b><p>${esc(g.trap)}</p></div>${g.from?`<a class="grammar-link" href="#${g.from}">같은 유형의 특별 지문 →</a>`:''}</article>`}
const grammarMethods={"수일치": "① 수식어를 괄호로 묶는다 → ② 주어의 중심 명사 또는 명사절 전체를 찾는다 → ③ 단수·복수를 판단한다 → ④ 본동사를 맞춘다.", "분사·태": "① 본동사가 이미 있는지 확인한다 → ② 밑줄이 꾸미거나 설명하는 대상을 찾는다 → ③ 그 대상이 행위를 하면 -ing, 행위를 받으면 p.p.인지 검토한다 → ④ 뒤 목적어와 전치사도 확인한다.", "접속사·관계사": "① 절의 경계를 나눈다 → ② 뒤 절의 주어·목적어·보어가 모두 있는지 본다 → ③ 선행사가 있는지 찾는다 → ④ 빠진 성분과 필요한 전치사를 복원한다. whether는 ‘~인지’라는 의미까지 확인한다.", "대명사·재귀대명사": "① 대명사의 지시 대상을 명사로 되돌린다 → ② 단수·복수를 확인한다 → ③ 같은 절의 주어와 대상이 같으면 재귀형을 검토한다 → ④ those/that은 비교 대상의 수를 확인한다.", "형용사·부사": "① 밑줄이 꾸미는 단어를 찾는다 → ② 동사·형용사·부사를 꾸미면 부사인지 확인한다 → ③ 주어나 목적어의 상태를 나타내는 보어라면 형용사인지 확인한다. be + p.p.는 수동 동사구일 수 있다.", "비교·병렬": "① as ... as, either ... or, and의 짝을 찾는다 → ② 각 짝이 묶는 단위를 확인한다 → ③ 비교절의 생략된 말을 복원한다 → ④ 형태뿐 아니라 연결되는 의미도 맞는지 본다.", "준동사": "① 본동사와 준동사를 구분한다 → ② enough to, judge O to be처럼 주변 구조를 복원한다 → ③ to부정사의 의미상 주어와 역할을 확인한다.", "강조·도치": "① do 강조인지 It is ... that 강조인지 찾는다 → ② 강조 장치를 빼고 기본 문장으로 돌린다 → ③ do 뒤 동사원형과 강조 대상의 수를 확인한다.", "가정법": "① if절과 결과절을 함께 본다 → ② 실제 사실인지 반대 상황의 가정인지 판단한다 → ③ 과거 형태가 과거 시간을 뜻하는지 비현실성을 뜻하는지 구분한다.", "문장 뼈대·동사": "① 문장 전체에서 시제·수일치를 가진 본동사를 찾는다 → ② -ing와 p.p. 수식어를 제외한다 → ③ 동사가 없다면 필요한 시제와 주어 수에 맞는 동사를 넣는다."};
function specialContent(p){if(section==='brief')return heading('GRAMMAR SPECIAL / BRIEF','내용은 간단하게','내용을 이해한 뒤 어법과 문장 연결에 집중하세요.')+`<div class="takeaway"><span>한 문장 핵심</span><p>${esc(p.central)}</p></div>`+p.easy.map(t=>`<article class="content-card"><p>${esc(t)}</p></article>`).join('')+`<div class="content-card"><b>이 차이만 기억하기</b><p>${esc(p.tip)}</p></div><div class="arrow-flow">${p.sentences.map(s=>`<span>${range(s.n)} ${esc(s.role)} · ${esc(s.why)}</span>`).join('<i>↓</i>')}</div>`;
if(section==='grammar')return heading('GRAMMAR SPECIAL / 35 POINTS','밑줄 어법 집중 분석','맞는 표현도 왜 맞는지 확인하세요. S 버튼을 누르면 원문의 해당 문장이 표시됩니다.')+`<div class="takeaway"><span>공부 순서</span><p>문장 뼈대 확인 → 밑줄의 역할 판단 → 수식 대상·능동/수동 확인 → 오답 형태와 비교</p></div>`+p.grammarPoints.map(grammarCard).join('')+note(p);
return heading('GRAMMAR SPECIAL / TRANSFER','이 지문에서 다른 문장으로','표현을 외우기보다 같은 유형의 판단 순서를 익히세요.')+p.grammarPoints.map(g=>`<article class="content-card"><h3>${esc(g.category)} ${range(g.n)}</h3><p>${esc(grammarMethods[g.category])}</p><p><b>이 문장에 적용</b> · ${esc(g.rule)}</p><div class="reason"><b>형태를 바꿔 낼 때 주의할 점</b><p>${esc(g.trap)}</p></div></article>`).join('')+`<div class="takeaway"><span>공통 점검</span><p>① 본동사가 있는가? ② 주어의 중심 명사는 무엇인가? ③ 관계절 안에 어떤 성분이 빠졌는가? ④ 분사의 주체가 행위를 하는가, 받는가? ⑤ 대명사는 누구를 받고 무엇을 꾸미는가?</p></div>`+note(p);}
function answerExplanation(p){const parts=p.answer.split(/(?=[①②③④⑤])/).map(x=>x.trim()).filter(Boolean);return `<div class="choice-reasons">${parts.map(x=>`<p>${esc(x)}</p>`).join('')}</div>`}
function note(p){return `<section class="note"><label for="note">${p.specialGrammar?'나의 어법 메모':'나의 연결 메모'}</label><p>${p.specialGrammar?'주어·본동사·수식 대상과 헷갈린 오답 형태를 적어 보세요.':'헷갈렸던 연결이나 다시 읽을 이유를 남겨 보세요.'}</p><textarea id="note" placeholder="${p.specialGrammar?'예: patients가 주어이므로 know, system은 수식어 안의 명사':'예: However 앞의 통념과 뒤의 실제 주장을 구분하기'}">${esc(getMark(p.id).note||'')}</textarea><small id="noteState">이 브라우저에 자동 저장됩니다.</small></section>`}
function photos(){$('#photoBody').innerHTML=current.photos.map(n=>`<figure><figcaption>${current.specialGrammar?'어법 PDF · '+current.sourcePage+'쪽':'자료 사진 '+String(n+1).padStart(2,'0')}</figcaption><img src="assets/sources/${String(n).padStart(2,'0')}.jpg" alt="${esc(current.title)}이 실린 자료 사진 ${n+1}" loading="lazy"></figure>`).join('');$('#photos').showModal()}
$('#closePhotos').onclick=()=>$('#photos').close();$('#photos').addEventListener('click',e=>{if(e.target===$('#photos'))$('#photos').close()});window.addEventListener('hashchange',route);route();
})();
